void StrBToF(char* str);
void WStrBToF(wchar_t* str);
void StrFToB(char* str);
void DeleteTree(const char* dir);
void CopyDirContent(const char* src, const char* dst);
void ParentDir(const char* file, char* out);
void ConfigPath(char* outPath);
void LogPath(char* outPath);
void UpdaterPath(char* outPath);
void SettingsPath(char* outPath);
void aas_path(char* outPath);
void add_to_startup_path(char* outPath);
void remove_from_startup_path(char* outPath);