static const char ConfigStr[] =
"// AltAppSwitcher config file\n"
"\n"
"// Possible key bindings values:\n"
"//     left alt\n"
"//     right alt\n"
"//     alt\n"
"//     tilde\n"
"//     left super (left windows)\n"
"//     right super (right windows)\n"
"//     left control\n"
"//     left shift\n"
"//     right shift\n"
"//     tab\n"
"//     none\n"
"\n"
"app hold key: left alt\n"
"next app key: tab\n"
"previous app key: tilde\n"
"window hold key: left alt\n"
"next window key: tilde\n"
"invert order key: left shift\n"
"\n"
"// Graphic options:\n"
"// Theme can be \"auto\" (matches windows theme), \"light\" or \"dark\".\n"
"// Scale controls icon size, expressed as a ratio, 1 being Windows default icon size.\n"
"theme: auto\n"
"scale: 2.5\n"
"\n"
"// Other options:\n"
"allow mouse: true\n"
"check for updates: true\n"
;